import "./globals.css";
import '@radix-ui/themes/styles.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavigationMenuWide } from "./components/NavigationMenuWide";
import { ThemeProvider } from "./components/theme-provider";

import ProgressBar from "./ProgressBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ProgressBar
            height="4px"
            color="rgb(156, 163, 175, 0.9)"
            options={{ showSpinner: true }}
          />
          <NavigationMenuWide />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
